language: bash

sudo: 'required'

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: mSj4SYM4weApU3Ct+nqdaHkLw0J/q5+VH1q0LYnviZ06UpRU/N6lricfu9ihgND2VJ+cwfuQpAegdI1cDFzxDRpZpnzU9Db4N7OW5cDkb8eHpy6XhjQYi5KqWfgamh2UwiqYGgoQBc4gXhGDlChjJQopM+qPesHO9y/ucFAjxdlkEHVdZKNYDiVfiOKCGBzDuP+PbOPiZiqQFBgmFs1YLLrrQ7y5dgdoiai2I72MAN0kngoNB9ZsUgtQ63WTdgPKJOiX+oQMMXgYoP0+9iIhS6/cKHs64Z7jPreYYuWWMTnQPdvaIgh4ASIhUE6FVI5SdFxmajVik8SMlRK1rQApQLJ9wOJammUJHCSI4jfEVQ5H2og9R3+BA0qspBQVZXMTCYfX10Up1tmL+Kev1Za335v2z046gzX4aTiWBxi1I9mYmnYKQiGuaIG5crkPodIAeS9HX/DulMUhPRpa0Djwi7ZJlCAzfuEGDgAlWt/oWfIw66unTY/G6cEaxeEbZ3Ho+bPy48dRxhYW5kRHR1OuHqqfNULYeAGm6AIF3ng+2GjvXh6rhqmstBh/myROqM3X7ofUzEJRo9ow+hDroZLE4mfavn4UAnQybN7FfzuJiOoYTmcws7JzYD8b/G+Aynjw04m0ojDDJN0fVgQ+qltMoCfFMhx8FscF/QjGo/T/zc4=
    template:
      - "Repo %{repository_slug} *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>)"
      - "%{author}: _%{commit_message}_"
      - "Execution time: *%{duration}*"
      - "Message: *%{message}*"
    on_success: always

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.0

before_install:
  - ./.travis/main.sh

# install:
#   - git clone https://github.com/litespeedtech/ols-docker-env.git
#   - docker build --tag litespeedtech/openlitespeed-beta:1.6.5.lh config/litespeed/1.6.5.lh
#   - docker build --tag litespeedtech/openlitespeed-beta:1.6.4.lh config/litespeed/1.6.4.lh
#   - docker-compose up -d

# before_script:
#   - docker image ls
#   - sleep 10

# script:  
#   - ./.travis/verify.sh

# after_success:
#   - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
#   - docker push litespeedtech/openlitespeed-beta:1.6.5.lh
#   - docker push litespeedtech/openlitespeed-beta:1.6.4.lh

# after_script:
#   - docker-compose stop
#   - docker-compose rm -f





